// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk6SQ7x3adGdS5Ypd5RPXEAG5aYD7Dz3o',
    appId: '1:150383526161:web:5591c6ed39d5925f790cb0',
    messagingSenderId: '150383526161',
    projectId: 'dohar-sho',
    authDomain: 'dohar-sho.firebaseapp.com',
    storageBucket: 'dohar-sho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZq-NFIGelxiLb68ZtMRfX2Y7kJsKKXA',
    appId: '1:150383526161:android:cd234c8b1c4f50f5790cb0',
    messagingSenderId: '150383526161',
    projectId: 'dohar-sho',
    storageBucket: 'dohar-sho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhpkOYpCTxvByYeR_GYb5K_cx6hMPRmo',
    appId: '1:150383526161:ios:b95ad3b6942ff083790cb0',
    messagingSenderId: '150383526161',
    projectId: 'dohar-sho',
    storageBucket: 'dohar-sho.firebasestorage.app',
    iosBundleId: 'com.example.doharShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAhpkOYpCTxvByYeR_GYb5K_cx6hMPRmo',
    appId: '1:150383526161:ios:b95ad3b6942ff083790cb0',
    messagingSenderId: '150383526161',
    projectId: 'dohar-sho',
    storageBucket: 'dohar-sho.firebasestorage.app',
    iosBundleId: 'com.example.doharShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk6SQ7x3adGdS5Ypd5RPXEAG5aYD7Dz3o',
    appId: '1:150383526161:web:291366524f0ef38d790cb0',
    messagingSenderId: '150383526161',
    projectId: 'dohar-sho',
    authDomain: 'dohar-sho.firebaseapp.com',
    storageBucket: 'dohar-sho.firebasestorage.app',
  );
}
